#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 26 14:34:30 2020

@author: begin

"""
import xarray as xr
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

var='tasmax'
stat1='sai_1981_2010_'#référence
b_pt='posttraite'

#saison n=position dans saison 0=DJF 1-JJA
n=3
saison=['DJF','JJA','MAM','SON']

path_obs=('/tank/begin/weighting/E_1_obs/traite/'+var)
files_obs= []
for i in os.listdir(path_obs):
    if os.path.isfile(os.path.join(path_obs,i)) and stat1 in i:
        files_obs.append(i)
        

#ouvrir dataarray des fichiers qui commence par stat1
da_obs=[]
for j in range(0,(len(files_obs))):
    da_obs.append(xr.open_dataarray(path_obs+'/'+files_obs[j]))


#créer un dictionnaire avec dataarray       
files_totale=files_obs
files_split=[]
dictio=[]
for i in range(0,len(files_totale)):
    files_split.append(files_totale[i].split('_'))
    dictio.append({'groupe':files_split[i][3],
                   'gcm':files_split[i][4],
                   'rcm':files_split[i][5],
                   'membre':files_split[i][6],
                   'resolution':files_split[i][7],
                   'rcp':files_split[i][8],
                   'variable':files_split[i][9],
                   'files':files_totale[i],
                   'data':da_obs[i]})

##faire dataframe avec dictionnaire
df=pd.DataFrame.from_dict(dictio)
data=[]
for i in range(len(df)):
    data.append(df['data'][i][n])
plt.figure(figsize=(12,6))   
x=[]
for i in range(len(df)):
    x.append(df['gcm'][i]+'_'+df['rcm'][i]+'_'+df['resolution'][i])
plt.plot(x,data,'.')
plt.xticks(rotation=270)
plt.grid(b=True)
#plt.minorticks_on()
plt.title('Température maximale saisonnière_'+saison[n]+'\nobservations')
plt.savefig('/tank/begin/weighting/plots/'+var+'_comparaison_obs_'+saison[n],bbox_inches='tight')

